# Generated by Django 3.0.8 on 2020-07-28 12:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_datetime', models.DateField(default=datetime.date.today)),
                ('delivery_datetime', models.DateField(default=datetime.date.today)),
                ('delivery_address', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('DELIVERED', 'delivered'), ('PROCESSED', 'processed'), ('CANCELLED', 'cancelled')], default='CREATED', max_length=9)),
                ('product_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.ProductSets')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myorders', to='api.Recipient')),
            ],
        ),
    ]
